#include <iostream>
#include <map>

using namespace std;


int main ()
{
    int t;  cin >> t;
    while(t--){
        int n, m;  cin >> n >> m;
        int a[n], b[m];
        for (int i = 0; i < n; i++)
            cin >> a[i];
        for (int i = 0; i < m; i++)
            cin >> b[i];
        int count = 0;
        for (int i = 0;i < n; i++){
            for (int j = 0;j < m;)
        }
    }
}
